[build]
  command = "echo 'No build command needed'"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/cart"
  to = "/cart.html"
  status = 200

[[redirects]]
  from = "/checkout"
  to = "/checkout.html"
  status = 200

[headers]
  # Enable CORS for all routes
  for = "/*"
    [[headers.values]]
      key = "Access-Control-Allow-Origin"
      value = "*"
    [[headers.values]]
      key = "Access-Control-Allow-Methods"
      value = "GET,PUT,POST,DELETE,OPTIONS"
    [[headers.values]]
      key = "Access-Control-Allow-Headers"
      value = "Content-Type, Authorization"

  # Enable CORS for functions
  for = "/.netlify/functions/*"
    [[headers.values]]
      key = "Access-Control-Allow-Origin"
      value = "*"
    [[headers.values]]
      key = "Access-Control-Allow-Methods"
      value = "GET,PUT,POST,DELETE,OPTIONS"
    [[headers.values]]
      key = "Access-Control-Allow-Headers"
      value = "Content-Type, Authorization"
    [[headers.values]]
      key = "Access-Control-Allow-Credentials"
      value = "true"
    [[headers.values]]
      key = "Access-Control-Max-Age"
      value = "86400"
