[build]
  command = "echo 'No build command needed'"
  publish = ""

[functions]
  directory = "netlify/functions"

[redirects]
  # Redirect all requests to the index.html file
  / = /index.html
  /cart = /cart.html
  /checkout = /checkout.html

[headers]
  # Enable CORS for the functions directory
  "/.netlify/functions/*" =
    - "Access-Control-Allow-Origin: *"
    - "Access-Control-Allow-Methods: GET,PUT,POST,DELETE,OPTIONS"
    - "Access-Control-Allow-Headers: Content-Type, Authorization"
